// ──────────────────────────────────────────
// 中国历史时间轴 · 数据层
// 字段说明：
//   dynastyData      — 主时间轴朝代节点
//   subTimelineData  — 次级时间轴断代事件（按朝代 ID 索引）
//   key_figures      — 核心历史人物
//   artifacts        — 代表性文物 / 出土遗迹
// ──────────────────────────────────────────

const dynastyData = [
  { id: 'shennong',   name: '三皇五帝',   start: '约前3000', end: '约前2070', pos: 2  },
  { id: 'xia',        name: '夏',         start: '约前2070', end: '约前1600', pos: 6  },
  { id: 'shang',      name: '商',         start: '约前1600', end: '约前1046', pos: 10 },
  { id: 'xizhou',     name: '西周',       start: '约前1046', end: '前771',    pos: 14 },
  { id: 'dongzhou',   name: '东周',       start: '前770',    end: '前256',    pos: 18 },
  { id: 'qin',        name: '秦',         start: '前221',    end: '前207',    pos: 22 },
  { id: 'xihan',      name: '西汉',       start: '前202',    end: '公元9',    pos: 26 },
  { id: 'xin',        name: '新朝',       start: '公元9',    end: '23',       pos: 30 },
  { id: 'donghan',    name: '东汉',       start: '25',       end: '220',      pos: 34 },
  { id: 'sanguo',     name: '三国',       start: '220',      end: '280',      pos: 39 },
  { id: 'xijin',      name: '西晋',       start: '265',      end: '316',      pos: 43 },
  { id: 'dongjin',    name: '东晋十六国', start: '317',      end: '420',      pos: 47 },
  { id: 'nanbei',     name: '南北朝',     start: '420',      end: '589',      pos: 51 },
  { id: 'sui',        name: '隋',         start: '581',      end: '618',      pos: 55 },
  { id: 'tang',       name: '唐',         start: '618',      end: '907',      pos: 59 },
  { id: 'wudai',      name: '五代十国',   start: '907',      end: '960',      pos: 64 },
  { id: 'beisong',    name: '北宋',       start: '960',      end: '1127',     pos: 68 },
  { id: 'nansong',    name: '南宋',       start: '1127',     end: '1279',     pos: 72 },
  { id: 'yuan',       name: '元',         start: '1271',     end: '1368',     pos: 76 },
  { id: 'ming',       name: '明',         start: '1368',     end: '1644',     pos: 80 },
  { id: 'qing',       name: '清',         start: '1644',     end: '1912',     pos: 85 },
  { id: 'minguo',     name: '中华民国',   start: '1912',     end: '1949',     pos: 90 },
  { id: 'zhongguo',   name: '中华人民共和国', start: '1949', end: '至今',    pos: 95 },
];

const subTimelineData = {
  shennong: [
    { name: '燧人氏',   era: '约前3000', desc: '钻木取火·结绳记事',    key_figures: [],               artifacts: [] },
    { name: '伏羲氏',   era: '',         desc: '创八卦·教渔猎',        key_figures: ['伏羲', '女娲'],    artifacts: ['八卦图'] },
    { name: '神农氏',   era: '',         desc: '尝百草·教农耕',        key_figures: ['炎帝'],           artifacts: ['耒耜', '彩陶'] },
    { name: '黄帝',     era: '约前2700', desc: '统一华夏·制礼乐',      key_figures: ['黄帝', '嫘祖', '仓颉'], artifacts: ['黄帝内经'] },
    { name: '颛顼',     era: '',         desc: '绝地天通·定历法',      key_figures: ['颛顼', '共工'],    artifacts: [] },
    { name: '帝喾',     era: '',         desc: '顺天恤民·明鬼神',      key_figures: ['帝喾'],           artifacts: [] },
    { name: '尧',       era: '约前2300', desc: '禅让之始·派羲和观天',   key_figures: ['尧', '羲和'],      artifacts: ['陶寺遗址'] },
    { name: '舜',       era: '约前2200', desc: '孝感动天·命禹治水',    key_figures: ['舜', '禹'],        artifacts: [] },
  ],
  xia: [
    { name: '禹',       era: '约前2070', desc: '治水功成·建夏',        key_figures: ['禹', '启'],        artifacts: ['二里头遗址'] },
    { name: '启',       era: '',         desc: '家天下·世袭始',        key_figures: ['启', '有扈氏'],    artifacts: [] },
    { name: '太康失国', era: '',         desc: '后羿代夏',             key_figures: ['太康', '后羿', '寒浞'], artifacts: [] },
    { name: '少康中兴', era: '',         desc: '复国·夏道复兴',        key_figures: ['少康'],           artifacts: [] },
    { name: '桀',       era: '约前1600', desc: '暴虐亡国·商汤伐夏',    key_figures: ['桀', '商汤', '妺喜'], artifacts: [] },
  ],
  shang: [
    { name: '商汤',     era: '约前1600', desc: '伐夏建商·作汤誓',      key_figures: ['商汤', '伊尹'],    artifacts: ['汤誓'] },
    { name: '盘庚',     era: '约前1300', desc: '迁都于殷·中兴商朝',    key_figures: ['盘庚'],           artifacts: ['殷墟遗址', '甲骨文'] },
    { name: '武丁',     era: '约前1250', desc: '武丁盛世·妇好征伐',    key_figures: ['武丁', '妇好', '傅说'], artifacts: ['后母戊鼎', '妇好墓'] },
    { name: '纣王',     era: '约前1075', desc: '暴虐失国·牧野之战',    key_figures: ['帝辛', '妲己', '比干'], artifacts: [] },
  ],
  xizhou: [
    { name: '武王伐纣', era: '约前1046', desc: '牧野之战·周朝建立',    key_figures: ['武王', '姜子牙', '周公'], artifacts: ['利簋'] },
    { name: '周公摄政', era: '',         desc: '制礼作乐·分封诸侯',    key_figures: ['周公旦', '召公奭'], artifacts: ['周礼'] },
    { name: '成康之治', era: '',         desc: '刑措不用·天下安宁',    key_figures: ['成王', '康王'],    artifacts: [] },
    { name: '国人暴动', era: '前841',    desc: '厉王出奔·共和行政',    key_figures: ['厉王', '召穆公'],  artifacts: ['遂公盨'] },
    { name: '宣王中兴', era: '前827',    desc: '北伐猃狁·南征荆蛮',    key_figures: ['宣王', '尹吉甫'],  artifacts: ['兮甲盘'] },
    { name: '幽王',     era: '前781',    desc: '烽火戏诸侯·犬戎灭周',  key_figures: ['幽王', '褒姒'],    artifacts: [] },
  ],
  dongzhou: [
    { name: '平王东迁', era: '前770',    desc: '定都洛邑·东周始',      key_figures: ['平王'],           artifacts: [] },
    { name: '春秋五霸', era: '前770-前476', desc: '齐桓·晋文·楚庄·吴阖闾·越勾践', key_figures: ['齐桓公', '晋文公', '楚庄王'], artifacts: ['青铜剑'] },
    { name: '孔子',     era: '前551-前479', desc: '儒家始祖·周游列国',  key_figures: ['孔子', '子路', '子贡'], artifacts: ['论语'] },
    { name: '战国七雄', era: '前475-前221', desc: '齐楚燕韩赵魏秦·百家争鸣', key_figures: ['商鞅', '孙膑', '屈原'], artifacts: ['曾侯乙编钟', '秦公镈'] },
    { name: '秦灭周',   era: '前256',    desc: '周赧王献地·东周亡',    key_figures: ['周赧王', '秦昭襄王'], artifacts: [] },
  ],
  qin: [
    { name: '秦始皇',   era: '前221',    desc: '统一六国·始称皇帝',    key_figures: ['嬴政', '李斯', '王翦'], artifacts: ['秦始皇陵', '秦诏版'] },
    { name: '废分封',   era: '',         desc: '行郡县·书同文·车同轨',  key_figures: ['李斯'],           artifacts: ['琅琊台刻石', '秦权'] },
    { name: '焚书坑儒', era: '前213',    desc: '李斯献策·思想统制',    key_figures: ['李斯', '扶苏'],    artifacts: [] },
    { name: '始皇驾崩', era: '前210',    desc: '沙丘之变·赵高专权',    key_figures: ['嬴政', '赵高', '李斯'], artifacts: [] },
    { name: '陈胜起义', era: '前209',    desc: '大泽乡揭竿·天下响应',   key_figures: ['陈胜', '吴广', '项梁'], artifacts: [] },
    { name: '秦亡',     era: '前207',    desc: '刘邦入关·子婴献玺',    key_figures: ['子婴', '刘邦', '项羽'], artifacts: [] },
  ],
  xihan: [
    { name: '刘邦建汉', era: '前202',    desc: '楚汉争霸·定都长安',    key_figures: ['刘邦', '萧何', '韩信'], artifacts: ['汉并天下瓦当'] },
    { name: '文景之治', era: '前180-前141', desc: '轻徭薄赋·与民休息', key_figures: ['文帝', '景帝', '贾谊'], artifacts: ['马王堆帛书'] },
    { name: '汉武帝',   era: '前141-前87',  desc: '独尊儒术·开疆拓土', key_figures: ['刘彻', '卫青', '霍去病'], artifacts: [] },
    { name: '张骞出使', era: '前138',    desc: '凿空西域·丝绸之路',    key_figures: ['张骞', '汉武帝'],   artifacts: ['丝绸之路遗迹'] },
    { name: '昭宣中兴', era: '前87-前49', desc: '吏治清明·匈奴来朝',   key_figures: ['宣帝', '霍光'],    artifacts: [] },
    { name: '王莽篡汉', era: '公元9',    desc: '外戚代汉·西汉亡',      key_figures: ['王莽', '孺子婴'],  artifacts: [] },
  ],
  xin: [
    { name: '王莽称帝', era: '公元9',    desc: '代汉立新·托古改制',    key_figures: ['王莽'],           artifacts: ['新莽铜嘉量'] },
    { name: '王田私属', era: '',         desc: '禁奴婢买卖·土地国有',   key_figures: ['王莽'],           artifacts: [] },
    { name: '绿林赤眉', era: '17',       desc: '饥民起义·天下大乱',    key_figures: ['王匡', '樊崇'],    artifacts: [] },
    { name: '新朝覆灭', era: '23',       desc: '义军入长安·王莽被杀',   key_figures: ['王莽', '刘秀'],    artifacts: [] },
  ],
  donghan: [
    { name: '光武中兴', era: '25',       desc: '刘秀称帝·定都洛阳',    key_figures: ['刘秀', '邓禹'],    artifacts: [] },
    { name: '明章之治', era: '57-88',    desc: '吏治清明·佛法东传',    key_figures: ['明帝', '章帝'],    artifacts: ['白马寺'] },
    { name: '蔡伦造纸', era: '105',      desc: '改进造纸术·文化传播',   key_figures: ['蔡伦'],           artifacts: ['蔡侯纸'] },
    { name: '张衡地动仪', era: '132',    desc: '候风地动仪·科技巅峰',   key_figures: ['张衡'],           artifacts: ['地动仪复原模型'] },
    { name: '黄巾起义', era: '184',      desc: '张角太平道·天下大乱',   key_figures: ['张角', '张宝', '张梁'], artifacts: [] },
    { name: '汉室衰亡', era: '220',      desc: '曹丕篡汉·献帝禅让',    key_figures: ['献帝', '曹丕', '董卓'], artifacts: [] },
  ],
  sanguo: [
    { name: '官渡之战', era: '200',      desc: '曹操破袁绍·统一北方',   key_figures: ['曹操', '袁绍', '许攸'], artifacts: [] },
    { name: '赤壁之战', era: '208',      desc: '孙刘联兵·天下三分',    key_figures: ['周瑜', '诸葛亮', '曹操'], artifacts: [] },
    { name: '三国鼎立', era: '220-222',  desc: '曹魏·蜀汉·孙吴',       key_figures: ['曹丕', '刘备', '孙权'], artifacts: [] },
    { name: '诸葛亮北伐', era: '228-234', desc: '六出祁山·鞠躬尽瘁',   key_figures: ['诸葛亮', '姜维', '司马懿'], artifacts: ['出师表'] },
    { name: '司马篡魏', era: '265',      desc: '司马炎代魏·晋朝始',    key_figures: ['司马炎', '司马昭'], artifacts: [] },
    { name: '吴亡·三分归晋', era: '280', desc: '王濬楼船下益州',        key_figures: ['孙皓', '王濬', '杜预'], artifacts: [] },
  ],
  xijin: [
    { name: '太康盛世', era: '280',      desc: '统一全国·短暂繁荣',    key_figures: ['司马炎'],         artifacts: [] },
    { name: '八王之乱', era: '291-306',  desc: '宗室相残·国力耗尽',    key_figures: ['司马伦', '司马颖', '贾南风'], artifacts: [] },
    { name: '永嘉之乱', era: '311',      desc: '匈奴攻陷洛阳·怀帝被俘', key_figures: ['怀帝', '刘渊', '石勒'], artifacts: [] },
    { name: '西晋灭亡', era: '316',      desc: '愍帝出降·衣冠南渡',    key_figures: ['愍帝', '刘曜'],    artifacts: [] },
  ],
  dongjin: [
    { name: '司马睿建东晋', era: '317',  desc: '定都建康·偏安江南',    key_figures: ['司马睿', '王导'],  artifacts: [] },
    { name: '淝水之战',   era: '383',    desc: '谢安破苻坚·草木皆兵',  key_figures: ['谢安', '谢玄', '苻坚'], artifacts: [] },
    { name: '五胡十六国', era: '304-439', desc: '匈奴·羯·鲜卑·氐·羌',  key_figures: ['石勒', '苻坚', '拓跋珪'], artifacts: [] },
    { name: '刘裕代晋',   era: '420',    desc: '刘裕建宋·东晋亡',      key_figures: ['刘裕'],           artifacts: [] },
  ],
  nanbei: [
    { name: '南北朝对峙', era: '420-589', desc: '南朝宋齐梁陈·北朝魏齐周', key_figures: ['刘裕', '萧道成', '拓跋焘'], artifacts: [] },
    { name: '北魏孝文帝', era: '471-499', desc: '迁都洛阳·汉化改革',    key_figures: ['拓跋宏', '冯太后'], artifacts: ['龙门石窟'] },
    { name: '六镇起义',   era: '523',    desc: '军阀崛起·北魏分裂',    key_figures: ['尔朱荣', '高欢', '宇文泰'], artifacts: [] },
    { name: '杨坚代周',   era: '581',    desc: '北周静帝禅位·隋朝始',  key_figures: ['杨坚', '静帝'],    artifacts: [] },
    { name: '隋灭陈',     era: '589',    desc: '南北统一·三百年分裂终结', key_figures: ['杨广', '陈叔宝'], artifacts: [] },
  ],
  sui: [
    { name: '开皇之治', era: '581-600',  desc: '杨坚改革·府兵均田',    key_figures: ['杨坚', '高颎'],    artifacts: [] },
    { name: '科举制创立', era: '605',     desc: '分科取士·打破门阀',    key_figures: ['杨广'],           artifacts: [] },
    { name: '大运河',     era: '605-610', desc: '贯通南北·连接五水',    key_figures: ['杨广', '宇文恺'],  artifacts: ['大运河'] },
    { name: '炀帝暴政',   era: '',        desc: '三征高丽·民怨沸腾',    key_figures: ['杨广'],           artifacts: [] },
    { name: '隋朝覆亡',   era: '618',     desc: '李渊入长安·隋亡',     key_figures: ['杨广', '李渊', '宇文化及'], artifacts: [] },
  ],
  tang: [
    { name: '李渊建唐',   era: '618',     desc: '削平群雄·统一天下',    key_figures: ['李渊', '李世民', '李建成'], artifacts: [] },
    { name: '贞观之治',   era: '627-649', desc: '太宗李世民·万国来朝',  key_figures: ['李世民', '魏征', '房玄龄'], artifacts: ['昭陵六骏'] },
    { name: '武则天称帝', era: '690',     desc: '改国号为周·唯一女皇',  key_figures: ['武则天', '狄仁杰'], artifacts: ['乾陵无字碑'] },
    { name: '开元盛世',   era: '713-741', desc: '玄宗·李杜文章·盛极一时', key_figures: ['李隆基', '姚崇', '宋璟'], artifacts: [] },
    { name: '安史之乱',   era: '755-763', desc: '安禄山反·由盛转衰',    key_figures: ['安禄山', '郭子仪', '杨贵妃'], artifacts: [] },
    { name: '唐末乱世',   era: '875-907', desc: '黄巢起义·朱温篡唐',    key_figures: ['黄巢', '朱温'],    artifacts: [] },
  ],
  wudai: [
    { name: '五代更迭',   era: '907-960',    desc: '梁唐晋汉周·五十四年五朝换', key_figures: ['朱温', '李存勖', '石敬瑭'], artifacts: [] },
    { name: '十国割据',   era: '902-979',    desc: '南方九国加北汉·各据一方', key_figures: ['李煜', '钱镠'], artifacts: [] },
    { name: '幽云十六州', era: '936',        desc: '石敬瑭割地·燕云入辽',    key_figures: ['石敬瑭', '耶律德光'], artifacts: [] },
    { name: '后周改革',   era: '951-960',    desc: '柴荣励精图治·赵匡胤陈桥兵变', key_figures: ['柴荣', '赵匡胤'], artifacts: [] },
  ],
  beisong: [
    { name: '陈桥兵变',   era: '960',      desc: '黄袍加身·杯酒释兵权',    key_figures: ['赵匡胤', '赵普'],  artifacts: [] },
    { name: '澶渊之盟',   era: '1004',     desc: '宋辽和议·百年和平',      key_figures: ['真宗', '寇准'],    artifacts: [] },
    { name: '庆历新政',   era: '1043',     desc: '范仲淹改革·先天下之忧',   key_figures: ['范仲淹', '欧阳修'], artifacts: ['岳阳楼记'] },
    { name: '王安石变法', era: '1069',     desc: '富国强兵·新旧党争',      key_figures: ['王安石', '司马光', '苏轼'], artifacts: [] },
    { name: '靖康之耻',   era: '1127',     desc: '金灭北宋·徽钦二帝北狩',   key_figures: ['徽宗', '钦宗', '李纲'], artifacts: ['清明上河图'] },
  ],
  nansong: [
    { name: '赵构建南宋', era: '1127',     desc: '定都临安·偏安江南',      key_figures: ['赵构', '宗泽'],    artifacts: [] },
    { name: '岳飞北伐',   era: '1140',     desc: '直捣黄龙·莫须有之冤',    key_figures: ['岳飞', '秦桧', '韩世忠'], artifacts: ['满江红'] },
    { name: '隆兴和议',   era: '1164',     desc: '宋金再和·叔侄之称',      key_figures: ['孝宗'],           artifacts: [] },
    { name: '宋学兴盛',   era: '',         desc: '朱熹理学·陆九渊心学',     key_figures: ['朱熹', '陆九渊'],  artifacts: ['四书章句集注'] },
    { name: '宋元战争',   era: '1235-1279', desc: '忽必烈南征·崖山蹈海',   key_figures: ['文天祥', '陆秀夫', '张世杰'], artifacts: [] },
  ],
  yuan: [
    { name: '忽必烈建元', era: '1271',     desc: '取易经·大元',            key_figures: ['忽必烈', '刘秉忠'], artifacts: [] },
    { name: '灭南宋',     era: '1279',     desc: '崖山海战·陆秀夫负帝投海', key_figures: ['陆秀夫', '张弘范'], artifacts: [] },
    { name: '行省制度',   era: '',         desc: '全国设行省·影响至今',     key_figures: ['忽必烈'],         artifacts: [] },
    { name: '马可波罗',   era: '1275-1292', desc: '游记传世·沟通东西',     key_figures: ['马可波罗', '忽必烈'], artifacts: ['马可波罗游记'] },
    { name: '红巾军起义', era: '1351',     desc: '元末民变·天下动荡',      key_figures: ['韩山童', '刘福通', '朱元璋'], artifacts: [] },
    { name: '元亡',       era: '1368',     desc: '朱元璋北伐·顺帝北逃',    key_figures: ['朱元璋', '徐达', '顺帝'], artifacts: [] },
  ],
  ming: [
    { name: '洪武之治',   era: '1368-1398', desc: '朱元璋开国·废丞相设内阁', key_figures: ['朱元璋', '刘基', '李善长'], artifacts: [] },
    { name: '永乐盛世',   era: '1402-1424', desc: '朱棣迁都北京·修永乐大典', key_figures: ['朱棣', '解缙', '郑和'], artifacts: ['永乐大典', '故宫'] },
    { name: '郑和下西洋', era: '1405-1433', desc: '七下西洋·远达非洲',      key_figures: ['郑和', '朱棣'],    artifacts: ['郑和宝船模型'] },
    { name: '万历中兴',   era: '1573-1582', desc: '张居正一条鞭法改革',     key_figures: ['张居正', '万历帝'], artifacts: [] },
    { name: '崇祯亡国',   era: '1644',      desc: '李自成破北京·清军入关', key_figures: ['崇祯帝', '李自成', '吴三桂'], artifacts: [] },
  ],
  qing: [
    { name: '清兵入关',   era: '1644',      desc: '吴三桂引清·顺治定鼎',    key_figures: ['多尔衮', '顺治帝', '吴三桂'], artifacts: [] },
    { name: '康乾盛世',   era: '1661-1796',  desc: '康熙·雍正·乾隆·疆域辽阔', key_figures: ['康熙', '雍正', '乾隆'], artifacts: ['四库全书', '圆明园'] },
    { name: '鸦片战争',   era: '1840',       desc: '英国东来·签订南京条约',  key_figures: ['林则徐', '道光帝'], artifacts: ['虎门炮台'] },
    { name: '洋务运动',   era: '1861-1895',  desc: '师夷长技·甲午一战成空',  key_figures: ['李鸿章', '张之洞', '左宗棠'], artifacts: ['江南制造总局'] },
    { name: '戊戌变法',   era: '1898',       desc: '百日维新·康梁变法',      key_figures: ['光绪帝', '康有为', '梁启超'], artifacts: [] },
    { name: '辛亥革命',   era: '1911',       desc: '武昌起义·终结帝制',      key_figures: ['孙中山', '黄兴', '袁世凯'], artifacts: ['武昌起义军政府旧址'] },
  ],
  minguo: [
    { name: '中华民国建立', era: '1912',     desc: '孙中山就任临时大总统',    key_figures: ['孙中山', '袁世凯'], artifacts: ['中华民国临时约法'] },
    { name: '北伐战争',     era: '1926-1928', desc: '国民革命军统一中国',     key_figures: ['蒋介石', '周恩来', '叶挺'], artifacts: [] },
    { name: '十年建设',     era: '1927-1937', desc: '南京国民政府·黄金十年',  key_figures: ['蒋介石'],         artifacts: [] },
    { name: '抗日战争',     era: '1937-1945', desc: '全面抗战·十四年浴血',    key_figures: ['毛泽东', '蒋介石', '朱德'], artifacts: [] },
    { name: '国共内战',     era: '1945-1949', desc: '决定中国命运之战',        key_figures: ['毛泽东', '蒋介石'], artifacts: [] },
  ],
  zhongguo: [
    { name: '开国大典', era: '1949',      desc: '中华人民共和国成立',        key_figures: ['毛泽东', '周恩来', '朱德'], artifacts: ['五星红旗'] },
    { name: '改革开放', era: '1978',      desc: '十一届三中全会·经济腾飞',   key_figures: ['邓小平'],         artifacts: [] },
    { name: '港澳回归', era: '1997-1999', desc: '香港·澳门回归祖国',        key_figures: ['江泽民', '董建华'], artifacts: [] },
    { name: '加入世贸', era: '2001',      desc: '融入全球经济体系',          key_figures: ['江泽民', '朱镕基'], artifacts: [] },
    { name: '新时代',   era: '2012',      desc: '中华民族复兴之路',          key_figures: ['习近平'],         artifacts: [] },
  ],
};
